apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: q2g1o0upp-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/q2g1o0upp-dotnet-basic-gitops