apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: q2g1o0upp-dotnet-basic
  janus-idp.io/tekton: q2g1o0upp-dotnet-basic
  backstage.io/kubernetes-id: q2g1o0upp-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: q2g1o0upp-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
